# syntax=docker/dockerfile:1.11
# This file is generated by Dofigen v2.5.1
# See https://github.com/lenra-io/dofigen

# muslrust
FROM clux/muslrust@sha256:f96654a4c624ce96da9adb3587164ef4bf945c6492873db22feec3428a0eaf25 AS muslrust
ARG APP_NAME=shiibot_rs
ARG BUILD_ARGS=--verbose
ARG CARGO_TARGET=x86_64-unknown-linux-musl
ARG TARGETPLATFORM=linux/amd64
LABEL \
    org.opencontainers.image.base.digest="sha256:f96654a4c624ce96da9adb3587164ef4bf945c6492873db22feec3428a0eaf25" \
    org.opencontainers.image.base.name="docker.io/clux/muslrust:stable"
WORKDIR /app
RUN \
    --mount=type=bind,target=Cargo.toml,source=Cargo.toml \
    --mount=type=bind,target=Cargo.lock,source=Cargo.lock \
    --mount=type=bind,target=src/,source=src/ \
    --mount=type=cache,target=/home/rust/.cargo,sharing=locked \
    --mount=type=cache,target=/app/target,sharing=locked \
    <<EOF
if [ "${TARGETPLATFORM}" = "linux/amd64" ]; then
  export CARGO_TARGET="x86_64-unknown-linux-musl"
elif [ "${TARGETPLATFORM}" = "linux/arm64" ]; then
  export CARGO_TARGET="aarch64-unknown-linux-musl"
fi
cargo build --release ${BUILD_ARGS}
mv target/${CARGO_TARGET}/release/${APP_NAME} /tmp/
EOF

# runtime
FROM scratch AS runtime
ARG APP_NAME=shiibot_rs
LABEL io.dofigen.version="2.5.1"
ENV PATH="/bin"
COPY \
    --from=muslrust \
    --chown=1000:1000 \
    --link \
    "/tmp/${APP_NAME}" "/bin/"
USER 1000:1000
ENTRYPOINT ["/bin/shiibot_rs"]
